export const weatherConditions = {
  s01d: require('./Assets/ic_clear.png'),
  s02d: require('./Assets/ic_light_clouds.png'),
  s03d: require('./Assets/ic_cloudy.png'),
  s04d: require('./Assets/ic_cloudy.png'),
  s09d: require('./Assets/ic_light_rain.png'),
  s10d: require('./Assets/ic_rain.png'),
  s11d: require('./Assets/ic_storm.png'),
  s13d: require('./Assets/ic_snow.png'),
  s50d: require('./Assets/ic_fog.png'),
  img01d: require('./Assets/art_clear.png'),
  img02d: require('./Assets/art_light_clouds.png'),
  img03d: require('./Assets/art_clouds.png'),
  img04d: require('./Assets/art_clouds.png'),
  img09d: require('./Assets/art_light_rain.png'),
  img10d: require('./Assets/art_rain.png'),
  img11d: require('./Assets/art_storm.png'),
  img13d: require('./Assets/art_snow.png'),
  img50d: require('./Assets/art_fog.png'),
};